apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: sre
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: renaudhager/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: efcloud
        - name: GITHUB_REPOSITORY
          value: sre-ansible-role-http-proxy
        - name: GITHUB_PAT # stored separately in a Kubernetes secret
          valueFrom:
            secretKeyRef:
              name: github-runner
              key: token
        - name: RUNNER_LABELS
          value: k8s,test
